---
# tasks file for disable-swap
- name: Disabling swap on hosts...
  become: yes
  shell: swapoff -a

- name: Disabling swap from fstab...
  become: yes
  replace:
    path: /etc/fstab
    regexp: '^([^#].*?\sswap\s+sw\s+.*)$'
    replace: '# \1'  
